<?php
 $aik =  array (
  'sitename' => '大象影院',
  'pcdomain' => 'http://www.510mei.com',
  'title' => '大象影院-免VIP抢先观看最新好看的电影和电视剧',
  'keywords' => '大象影院,电视直播网站,零八影院快播,高清云影视,云点播,免费看视频,湖南卫视直播,80电影网,最新电影天堂免费在线观看',
  'description' => '大象影院,热剧快播,最好看的剧情片尽在﻿大象影院,高清云影视免费为大家提供最新最全的免费电影，电视剧，综艺，动漫无广告在线云点播，以及电视直播',
  'icp' => '国ICP备18888888号',
  'foot' => '本站提供的最新电影和电视剧资源均系收集于各大视频网站,本站只提供web页面服务,并不提供影片资源存储,也不参与录制、上传</br>若本站收录的节目无意侵犯了贵司版权，请给网页底部邮箱地址来信,我们会及时处理和回复,谢谢。',
  'tongji' => '<script src="" language="JavaScript"></script>',
  'hometopnotice' => '',
  'path' => '',
  'mobiledomain' => '',
  'jiekou1' => 'http://api.baiyug.cn/vip/?url=',
  'jiekou2' => 'https://api.47ks.com/webcloud/?v=',
  'jiekou3' => 'http://www.efunfilm.com/yunparse/index.php?url=',
  'jiekou4' => 'http://api.nepian.com/ckparse/?url=',
  'jiekou5' => 'http://aikan-tv.com/?url=',
  'jiekou6' => 'http://j.zz22x.com/jx/?url=',
  'jiekou7' => 'http://jiexi.071811.cc/jx2.php?url=',
  'jiekou8' => 'http://api.wlzhan.com/sudu/?url=',
  'jiekou9' => 'http://api.xfsub.com/index.php?url=',
  'jiekou10' => 'http://api.wlzhan.com/sudu/?url=',
  'admin_name' => 'admin',
  'admin_pass' => '3ceb0e9fb16f8673c35f707e8657124a',
  'admin_email' => 'admin@admin.com',
  'logo_dh' => '<img src="images/logo.png">',
  'logo_ss' => '<img id="imgsrc" src="images/sologo.png">',
  'movie_ad' => '<a href="http://vip11.woaik.com" target="_blank"><img src="images/dc5c7986daef50c.gif" style="width:100%"></a>',
  'tv_ad' => '<a href="http://www.510mei.com" target="_blank"><img src="images/dc5c7986daef50c.gif" style="width:100%"></a>',
  'zongyi_ad' => '<a href="http://www.510mei.com" target="_blank"><img src="images/dc5c7986daef50c.gif" style="width:100%"></a>',
  'dongman_ad' => '<a href="http://www.510mei.com" target="_blank"><img src="images/dc5c7986daef50c.gif" style="width:100%"></a>',
  'jiazai_ad' => '<a href="http://www.510mei.com" target="_blank"><img src="images/jiazai.png" width="100%"></a>',
  'zfb_ad' => '<img src="images/zfb.png">',
  'wx_ad' => '<img src="images/wx.png">',
  'cebian1_ad' => '<a class="style02" href="" target="_blank"><strong>关注微信</strong><div class="article-wechats"> </br> <img src="images/qrcode.png"></div> </a>',
  'cebian3_ad' => '<h3>广告赞助</h3>			
<div class="textwidget"><a href="http://www.58renqifu.com/userreg/register/6605/a7459479d2f7053b79d20888f0552f1f" target="_blank"><img src="images/jianzhi.png" width="100%"></a>',
  'weixin_ad' => '<img src="images/qrcode.png">',
  'end_ad' => '<a href="http://www.510mei.com"><span><img src="/images/gouwu.png"/>购物</span></a>',
  'hometopright' => '',
  'homelink' => '',
  'sort' => '1,2,3,4,5,6,7,8,9,10',
  'joinhotkey' => '0',
);
?>